services:
  db:
    image: postgres:17 # You can specify a different version if needed
    container_name: express-money-tracker-db
    restart: always
    environment:
      POSTGRES_DB: express-money-tracker-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: